/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasialumni202557201008;

import com.formdev.flatlaf.FlatLightLaf; //mengatur tema flat terang
import com.mysql.cj.jdbc.PreparedStatementWrapper; //LIBARY BAAWAN JAVA untuk menghubungkan java ke database
import javax.swing.UIManager; // untuk mengatur tampilan UI aplikasi
import javax.swing.UnsupportedLookAndFeelException;
import java.sql.Connection; // untuk menghubungkan antar java dengan mysql
import java.sql.PreparedStatement; // untuk menjalankan query/perintah SQL 
import java.sql.SQLException; //untuk menangkap error yang terjadi saat java berinteraksi dengan mysql
import java.sql.ResultSet;//menampung hasil query SELECT dari database
import javax.swing.JOptionPane; //untuk menampilkan pop up

/**
 *
 * @author Acer
 */
public class fLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(fLogin.class.getName());

    /**
     * Creates new form fLogin
     */
    public fLogin() { //tempat konstruktor
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLogin = new javax.swing.JPanel();
        lblGambar = new javax.swing.JLabel();
        lblUserLogin = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPasswors = new javax.swing.JLabel();
        tUserName = new javax.swing.JTextField();
        tPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblclose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pLogin.setBackground(new java.awt.Color(51, 153, 255));

        lblGambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/pexels-artempodrez-6779410.jpg"))); // NOI18N

        lblUserLogin.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 24)); // NOI18N
        lblUserLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserLogin.setText("User Login");

        lblUserName.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName.setText("Username");

        lblPasswors.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        lblPasswors.setForeground(new java.awt.Color(255, 255, 255));
        lblPasswors.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPasswors.setText("Password");

        btnLogin.setBackground(new java.awt.Color(0, 102, 255));
        btnLogin.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        lblclose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/close 22.png"))); // NOI18N
        lblclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pLoginLayout = new javax.swing.GroupLayout(pLogin);
        pLogin.setLayout(pLoginLayout);
        pLoginLayout.setHorizontalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addComponent(lblGambar)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pLoginLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPasswors)
                            .addComponent(lblUserName)
                            .addComponent(tUserName)
                            .addComponent(tPassword)
                            .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLoginLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblclose)
                        .addGap(14, 14, 14))
                    .addGroup(pLoginLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(lblUserLogin)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pLoginLayout.setVerticalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addComponent(lblGambar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pLoginLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblclose)
                .addGap(58, 58, 58)
                .addComponent(lblUserLogin)
                .addGap(76, 76, 76)
                .addComponent(lblUserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblPasswors)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pLogin, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcloseMouseClicked
        // TODO add your handling code here:
        System.exit(0); // icon (X) BERFUNGSI untuk keluar dari frame login
    }//GEN-LAST:event_lblcloseMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here
      //saat tombol login di klik maka akan terjadi proses ini:
        //mengambil teks yang dimasukkan user pada field Username
            String username = tUserName.getText();
            //mengambil teks yang dimasukkan user pada field Password
            String password = tPassword.getText();
            //Periksa apakah username dan password tidak kosong?
            if (username.length() != 0 && password.length()!= 0)  {
        
                try {
                    //Query SQL untuk mencari username dan password (dihash dengan MD5)
                    String sql = "SELECT * FROM user WHERE username=? AND password=md5(?)";
                    //Buat koneksi ke database
                    Connection con = koneksi.konek();
                    //Siapkan statement SQL dengan parameter
                    PreparedStatement ps = con.prepareStatement(sql);
                    //Isi string pertama dengan username
                    ps.setString(1, username);
                    //isi string kedua dengan password yang akan di-hash MD5 di sisi database
                    ps.setString(2, password);
                    //Jalankan query dan ambil hasilnya
                    ResultSet rs = ps.executeQuery();
                    //Buka form Dashboard
                    if (rs.next()) {
                        //tutup frame login
                        dispose();
                        //membuka frame dashboard
                        new fDashboard().setVisible(true);
                    } else {
                        //jika data tidak ditemukan , tampilkan pesan error
                        JOptionPane.showMessageDialog(null, "Username/password salah");
                    }                    
                } catch (SQLException sQLException) {
                    //jika terjadi kesalahan SQL, tampilkan pesan error
                    JOptionPane.showMessageDialog(null, sQLException.getMessage());
                }
               
            }else {
                // Jika username atau password kosong , berikan peringatan ke user
                JOptionPane.showMessageDialog(null, "Username/password tidak boleh kosong");
   
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.put("Button.arc",15);
            UIManager.put("TextComponent.arc",15);
            UIManager.put("Button.borderWidth",0);
            UIManager.put("Component.borderWidth",0);
            UIManager.put("Component.fokusrWidth",0);
            UIManager.setLookAndFeel(new FlatLightLaf()); // untuk mengatur tema terang
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new fLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblGambar;
    private javax.swing.JLabel lblPasswors;
    private javax.swing.JLabel lblUserLogin;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblclose;
    private javax.swing.JPanel pLogin;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tUserName;
    // End of variables declaration//GEN-END:variables
}
