/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplikasialumni202557201008;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class panelSiswa extends javax.swing.JPanel {

    /**
     * Creates new form panelSiswa4
     */
    public panelSiswa() {
        initComponents();
    }
    void reset(){
        tNIS.setText(null);
        tNamaSiswa.setText(null);
        cJenisKelamin.setSelectedItem(null);
        tTempatLahir.setText(null);
        tTanggal.setCalendar(null);
        tHP.setText(null);
        cKelas.setSelectedItem(null);
        tAlamat.setText(null);
        tFotoPath.setText(null);
        tFoto.setIcon(null);
        tFoto.setText("Foto"); 
    }
    void comboKelas(){
        String sql = "SELECT* FROM kelas";
        
        Connection conn = koneksi.konek();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pHeaderSiswa = new javax.swing.JPanel();
        lblDataSiswa = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        pContentSiswa = new javax.swing.JPanel();
        pTampilan = new javax.swing.JPanel();
        pTombol = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        pInputan = new javax.swing.JPanel();
        tFoto = new javax.swing.JLabel();
        lblNis = new javax.swing.JLabel();
        tNIS = new javax.swing.JTextField();
        lblNama = new javax.swing.JLabel();
        tNamaSiswa = new javax.swing.JTextField();
        lblJenisKelamin = new javax.swing.JLabel();
        cJenisKelamin = new javax.swing.JComboBox<>();
        lblTempatLahir = new javax.swing.JLabel();
        tTempatLahir = new javax.swing.JTextField();
        lblTanggalLahir = new javax.swing.JLabel();
        lblHp = new javax.swing.JLabel();
        tHP = new javax.swing.JTextField();
        lblKelas = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAlamat = new javax.swing.JTextArea();
        tTanggal = new com.toedter.calendar.JDateChooser();
        cKelas = new javax.swing.JComboBox<>();
        pTable = new javax.swing.JPanel();
        pPath = new javax.swing.JPanel();
        tFotoPath = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSiswa = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 20));
        setMinimumSize(new java.awt.Dimension(1000, 861));
        setLayout(new java.awt.BorderLayout());

        pHeaderSiswa.setBackground(new java.awt.Color(51, 153, 255));
        pHeaderSiswa.setMinimumSize(new java.awt.Dimension(960, 40));
        pHeaderSiswa.setPreferredSize(new java.awt.Dimension(960, 40));
        pHeaderSiswa.setLayout(new java.awt.BorderLayout());

        lblDataSiswa.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        lblDataSiswa.setForeground(new java.awt.Color(255, 255, 255));
        lblDataSiswa.setText("Data Siswa");
        lblDataSiswa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        pHeaderSiswa.add(lblDataSiswa, java.awt.BorderLayout.LINE_START);

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/close 22.png"))); // NOI18N
        lblClose.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        pHeaderSiswa.add(lblClose, java.awt.BorderLayout.LINE_END);

        add(pHeaderSiswa, java.awt.BorderLayout.PAGE_START);

        pContentSiswa.setLayout(new java.awt.BorderLayout());

        pTampilan.setMinimumSize(new java.awt.Dimension(1235, 388));
        pTampilan.setPreferredSize(new java.awt.Dimension(1235, 388));
        pTampilan.setLayout(new java.awt.BorderLayout());

        pTombol.setMinimumSize(new java.awt.Dimension(960, 50));
        pTombol.setPreferredSize(new java.awt.Dimension(960, 50));

        btnTambah.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnTambah.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/plus white.png"))); // NOI18N
        btnTambah.setText("Tambah");

        btnUbah.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        btnUbah.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 14)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/edit white.png"))); // NOI18N
        btnUbah.setText("Ubah");

        btnHapus.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        btnHapus.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/hapus white.png"))); // NOI18N
        btnHapus.setText("Hapus");

        btnReset.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnReset.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/reset white.png"))); // NOI18N
        btnReset.setText("Reset");

        javax.swing.GroupLayout pTombolLayout = new javax.swing.GroupLayout(pTombol);
        pTombol.setLayout(pTombolLayout);
        pTombolLayout.setHorizontalGroup(
            pTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTombolLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(742, Short.MAX_VALUE))
        );
        pTombolLayout.setVerticalGroup(
            pTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTombolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pTampilan.add(pTombol, java.awt.BorderLayout.PAGE_END);

        pInputan.setMinimumSize(new java.awt.Dimension(1235, 338));
        pInputan.setPreferredSize(new java.awt.Dimension(1235, 338));

        tFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tFoto.setText("foto");
        tFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblNis.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblNis.setText("NIS");

        tNIS.setMinimumSize(new java.awt.Dimension(200, 34));
        tNIS.setPreferredSize(new java.awt.Dimension(200, 34));
        tNIS.addActionListener(this::tNISActionPerformed);

        lblNama.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblNama.setText("Nama");

        tNamaSiswa.setMinimumSize(new java.awt.Dimension(200, 34));
        tNamaSiswa.setPreferredSize(new java.awt.Dimension(200, 34));
        tNamaSiswa.addActionListener(this::tNamaSiswaActionPerformed);

        lblJenisKelamin.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblJenisKelamin.setText("Jenis Kelamin");

        cJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cJenisKelamin.setPreferredSize(new java.awt.Dimension(200, 34));

        lblTempatLahir.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblTempatLahir.setText("Tempat Lahir");

        tTempatLahir.setMinimumSize(new java.awt.Dimension(200, 34));
        tTempatLahir.setPreferredSize(new java.awt.Dimension(200, 34));
        tTempatLahir.addActionListener(this::tTempatLahirActionPerformed);

        lblTanggalLahir.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblTanggalLahir.setText("Tanggal Lahir");

        lblHp.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblHp.setText("HP");

        tHP.setMinimumSize(new java.awt.Dimension(200, 34));
        tHP.setPreferredSize(new java.awt.Dimension(200, 34));

        lblKelas.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblKelas.setText("Kelas");

        lblAlamat.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblAlamat.setText("Alamat");

        tAlamat.setColumns(20);
        tAlamat.setRows(5);
        jScrollPane2.setViewportView(tAlamat);

        tTanggal.setDateFormatString("yyyy-MM-dd\n");
        tTanggal.setMinimumSize(new java.awt.Dimension(200, 34));
        tTanggal.setPreferredSize(new java.awt.Dimension(200, 34));

        cKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cKelas.setPreferredSize(new java.awt.Dimension(200, 34));

        javax.swing.GroupLayout pInputanLayout = new javax.swing.GroupLayout(pInputan);
        pInputan.setLayout(pInputanLayout);
        pInputanLayout.setHorizontalGroup(
            pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInputanLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addComponent(tTempatLahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNis)
                    .addComponent(lblNama)
                    .addComponent(lblJenisKelamin)
                    .addComponent(lblTempatLahir)
                    .addComponent(lblTanggalLahir)
                    .addComponent(tNamaSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tNIS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cJenisKelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHp)
                    .addComponent(lblKelas)
                    .addComponent(lblAlamat)
                    .addComponent(tHP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                    .addComponent(cKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pInputanLayout.setVerticalGroup(
            pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInputanLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pInputanLayout.createSequentialGroup()
                        .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNis)
                            .addComponent(lblHp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tNIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNama)
                            .addComponent(lblKelas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tNamaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJenisKelamin)
                            .addComponent(lblAlamat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pInputanLayout.createSequentialGroup()
                                .addComponent(cJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTempatLahir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTanggalLahir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pTampilan.add(pInputan, java.awt.BorderLayout.CENTER);

        pContentSiswa.add(pTampilan, java.awt.BorderLayout.PAGE_START);

        pTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242), 20));
        pTable.setLayout(new java.awt.BorderLayout());

        pPath.setMinimumSize(new java.awt.Dimension(100, 30));
        pPath.setPreferredSize(new java.awt.Dimension(920, 30));

        tFotoPath.setText("jLabel1");

        javax.swing.GroupLayout pPathLayout = new javax.swing.GroupLayout(pPath);
        pPath.setLayout(pPathLayout);
        pPathLayout.setHorizontalGroup(
            pPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPathLayout.createSequentialGroup()
                .addComponent(tFotoPath)
                .addGap(0, 1172, Short.MAX_VALUE))
        );
        pPathLayout.setVerticalGroup(
            pPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPathLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(tFotoPath)
                .addContainerGap())
        );

        pTable.add(pPath, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.CardLayout());

        tblSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblSiswa);

        jPanel2.add(jScrollPane3, "card2");

        pTable.add(jPanel2, java.awt.BorderLayout.CENTER);

        pContentSiswa.add(pTable, java.awt.BorderLayout.CENTER);

        add(pContentSiswa, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tNamaSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaSiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaSiswaActionPerformed

    private void tTempatLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTempatLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTempatLahirActionPerformed

    private void tNISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNISActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cJenisKelamin;
    private javax.swing.JComboBox<String> cKelas;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDataSiswa;
    private javax.swing.JLabel lblHp;
    private javax.swing.JLabel lblJenisKelamin;
    private javax.swing.JLabel lblKelas;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNis;
    private javax.swing.JLabel lblTanggalLahir;
    private javax.swing.JLabel lblTempatLahir;
    private javax.swing.JPanel pContentSiswa;
    private javax.swing.JPanel pHeaderSiswa;
    private javax.swing.JPanel pInputan;
    private javax.swing.JPanel pPath;
    private javax.swing.JPanel pTable;
    private javax.swing.JPanel pTampilan;
    private javax.swing.JPanel pTombol;
    private javax.swing.JTextArea tAlamat;
    private javax.swing.JLabel tFoto;
    private javax.swing.JLabel tFotoPath;
    private javax.swing.JTextField tHP;
    private javax.swing.JTextField tNIS;
    private javax.swing.JTextField tNamaSiswa;
    private com.toedter.calendar.JDateChooser tTanggal;
    private javax.swing.JTextField tTempatLahir;
    private javax.swing.JTable tblSiswa;
    // End of variables declaration//GEN-END:variables
}
