/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplikasialumni202557201008;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Acer
 */
public class panelGuru extends javax.swing.JPanel {

    /**
     * Creates new form panelDashboard
     */
    public panelGuru() {
        initComponents(); 
        reset();//mengosongkan form input dan mengatur ulang komponen input
        load_tabel_guru();//memaut data dari database ke dalam tabel guru pada GUI
    }
    void reset(){ //method untuk mereset atau mengosongkan form input
        tNIP.setText(null); //kosaongkan field NIP
        tNIP.setEditable(true); //aktifkan kembali agar NIP bisa di edit
        tNamaGuru.setText(null); //kosongkan field nama guru
        cJenisKelamin.setSelectedItem(null); //reset pilihan jenis kelamin (combo box)
        tAlamat.setText(null); //kosongkan field alamat
    }
    void load_tabel_guru(){//method untuk memuat data dari tabel 'guru' ke dalam tabel GUI (tblGuru)
        DefaultTableModel mdl =new DefaultTableModel();//Membuat obejk mdl tabel baru 
        //menambahakan nama kolom ke dalam mdl tabel
        mdl.addColumn("NIP"); 
        mdl.addColumn("Nama Guru");
        mdl.addColumn("L/P");
        mdl.addColumn("Alamat");
        
        String sql = "SELECT * FROM guru"; //QUERY SQL untuk mengambil semua data dari tabel guru
        
        try {
            Connection conn = koneksi.konek();//membuka koneksi ke database

            Statement st = conn.createStatement();//membuat statement sql

            ResultSet rs = st.executeQuery(sql);//menjalankan query dan menyimpan hasilnya

            while (rs.next()) {//iterasi untuk setiap baris hasil query
                //mengambil nilai dari masing - masing kolom 
                String NIP = rs.getString("nip");
                String namaGuru = rs.getString("nama_guru");
                String jenisKelamin = rs.getString("gender");
                String alamat = rs.getString("alamat");

                Object[] baris = {NIP, namaGuru, jenisKelamin, alamat};//menyusun daata ke dalam array objek

                mdl.addRow(baris); //menambahkan data ke mdl tabel
            }
        } catch (SQLException sQLException) {
            //menampilkan pesan error jjika terjadi kegagalan megambil data dari database
            JOptionPane.showMessageDialog(null,"Gagal mengambil data");
        }
        
        tblGuru.setModel(mdl);//menampilkan data mdl ke dalam tabel GUI
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pHeaderGuru = new javax.swing.JPanel();
        lblDataGuru = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        pContentGuru = new javax.swing.JPanel();
        pInputan = new javax.swing.JPanel();
        lblNip = new javax.swing.JLabel();
        tNIP = new javax.swing.JTextField();
        tNamaGuru = new javax.swing.JTextField();
        lblNama = new javax.swing.JLabel();
        cJenisKelamin = new javax.swing.JComboBox<>();
        lblJenisKelamin = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        tAlamat = new javax.swing.JTextField();
        pTampilan = new javax.swing.JPanel();
        pTombol = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        pTabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGuru = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 20));
        setMinimumSize(new java.awt.Dimension(769, 451));
        setPreferredSize(new java.awt.Dimension(769, 451));
        setLayout(new java.awt.BorderLayout());

        pHeaderGuru.setBackground(new java.awt.Color(51, 153, 255));
        pHeaderGuru.setMinimumSize(new java.awt.Dimension(100, 40));
        pHeaderGuru.setPreferredSize(new java.awt.Dimension(100, 40));
        pHeaderGuru.setLayout(new java.awt.BorderLayout());

        lblDataGuru.setBackground(new java.awt.Color(51, 153, 255));
        lblDataGuru.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        lblDataGuru.setForeground(new java.awt.Color(255, 255, 255));
        lblDataGuru.setText("Data Guru");
        lblDataGuru.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        lblDataGuru.setOpaque(true);
        pHeaderGuru.add(lblDataGuru, java.awt.BorderLayout.LINE_START);

        lblClose.setBackground(new java.awt.Color(51, 153, 255));
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/close 22.png"))); // NOI18N
        lblClose.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        lblClose.setOpaque(true);
        pHeaderGuru.add(lblClose, java.awt.BorderLayout.LINE_END);

        add(pHeaderGuru, java.awt.BorderLayout.PAGE_START);

        pContentGuru.setLayout(new java.awt.BorderLayout());

        pInputan.setMinimumSize(new java.awt.Dimension(250, 371));
        pInputan.setPreferredSize(new java.awt.Dimension(250, 371));

        lblNip.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblNip.setText("NIP");

        lblNama.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblNama.setText("Nama");

        cJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan", "" }));

        lblJenisKelamin.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblJenisKelamin.setText("Jenis Kelamin");

        lblAlamat.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblAlamat.setText("Alamat");

        javax.swing.GroupLayout pInputanLayout = new javax.swing.GroupLayout(pInputan);
        pInputan.setLayout(pInputanLayout);
        pInputanLayout.setHorizontalGroup(
            pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInputanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAlamat)
                    .addComponent(lblJenisKelamin)
                    .addComponent(lblNama)
                    .addComponent(lblNip)
                    .addComponent(tNIP)
                    .addComponent(tNamaGuru)
                    .addComponent(cJenisKelamin, 0, 220, Short.MAX_VALUE)
                    .addComponent(tAlamat))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pInputanLayout.setVerticalGroup(
            pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInputanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNIP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNamaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJenisKelamin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAlamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pContentGuru.add(pInputan, java.awt.BorderLayout.LINE_START);

        pTampilan.setLayout(new java.awt.BorderLayout());

        btnTambah.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnTambah.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/plus white.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTambah.setMinimumSize(new java.awt.Dimension(72, 23));
        btnTambah.setPreferredSize(new java.awt.Dimension(72, 23));
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        btnUbah.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        btnUbah.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/edit white.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUbah.setMinimumSize(new java.awt.Dimension(72, 23));
        btnUbah.setPreferredSize(new java.awt.Dimension(72, 23));
        btnUbah.addActionListener(this::btnUbahActionPerformed);

        btnHapus.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        btnHapus.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/hapus white.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHapus.setMinimumSize(new java.awt.Dimension(72, 23));
        btnHapus.setPreferredSize(new java.awt.Dimension(72, 23));
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnReset.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnReset.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/reset white.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReset.setMinimumSize(new java.awt.Dimension(72, 23));
        btnReset.setPreferredSize(new java.awt.Dimension(72, 23));
        btnReset.addActionListener(this::btnResetActionPerformed);

        javax.swing.GroupLayout pTombolLayout = new javax.swing.GroupLayout(pTombol);
        pTombol.setLayout(pTombolLayout);
        pTombolLayout.setHorizontalGroup(
            pTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTombolLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pTombolLayout.setVerticalGroup(
            pTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTombolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pTampilan.add(pTombol, java.awt.BorderLayout.PAGE_END);

        pTabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242), 20));
        pTabel.setLayout(new java.awt.CardLayout());

        tblGuru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGuruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGuru);

        pTabel.add(jScrollPane1, "card2");

        pTampilan.add(pTabel, java.awt.BorderLayout.CENTER);

        pContentGuru.add(pTampilan, java.awt.BorderLayout.CENTER);

        add(pContentGuru, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        //mengambil input NIP dari text field tNIP
        String NIP = tNIP.getText();
        //mengambil input nama guru dari text field tNamaGuru
        String namaGuru = tNamaGuru.getText();
        //mengambil item yang dipilih dari combo box jenis kelamin
        String jenisKelamin = cJenisKelamin.getSelectedItem().toString();
        //mengambil input alamat dari text field tAlamat
        String alamat = tAlamat.getText();
        
        String jK = null; //menyiapkan variabel jk (jenis kelamin dalam format singkatan "L" atau "P")
        //Mengubah nilai jenis kelamin dari label menjadi format singkatan yang disimpan di database
        switch (jenisKelamin){
            case "Laki-Laki":
                jK="L";
                break;
            case "Perempuan":
                jK ="P";
                break;
            default:
                jK =null;
                break;
        }
        //menyusun perintah / query SQL untuk memasukkan data guru ke dalam tabel guru
        String sql ="INSERT INTO guru(nip, nama_guru, gender, alamat) VALUES(?,?,?,?)";
        
        try {
            //membuka koneksi ke database menggunakan method konek()
            Connection conn = koneksi.konek();
            //mempersiapkan query SQL dengan parameter (preparedStatment)
            PreparedStatement ps = conn.prepareStatement(sql);
            
            ps.setString(1, NIP);//mengisi parameter pertama dengan NIP
            
            ps.setString(2, namaGuru);//mengisi parameter kedua dengan Nama Guru
            
            ps.setString(3, jK);//mengisi parameter ketigaa dengan Jenis Kelamin("L" atau "P")
            
            ps.setString(4, alamat);//mengisi parameter ke empat dengan alamat
            
            ps.execute();//menjalankan perintah insert untuk menyimpan data ke database
            
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");//untuk menampilkan pesan bahwa data berhasil di simpan
        } catch (SQLException sQLException) {
            //menampilkan pesan jika terjadi kesalahan saat menyimpan data
            JOptionPane.showMessageDialog(null,"Data gagal disimpan");
        } 
        load_tabel_guru();//memuat ulang data guru di tabel tampilan
        
        reset(); //mereset semua input agar kosong kembali
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        //mengambil input NIP dari text field tNIP
        String NIP = tNIP.getText();
        //mengambil input nama guru dari text field tNamaGuru
        String namaGuru = tNamaGuru.getText();
        //mengambil item yang dipilih dari combo box jenis kelamin
        String jenisKelamin = cJenisKelamin.getSelectedItem().toString();
        //mengambil input alamat dari text field tAlamat
        String alamat = tAlamat.getText();
        
        String jK = null;//menyiapkan variabel jk (jenis kelamin dalam format singkatan "L" atau "P")
        //Mengubah nilai jenis kelamin dari label menjadi format singkatan yang disimpan di database
        switch (jenisKelamin){
            case "Laki-Laki":
                jK="L";
                break;
            case "Perempuan":
                jK ="P";
                break;
            default:
                jK =null;
                break;
        }
        //menyusun perintah / query SQL untuk mengubah data guru berdasarkan nip
        String sql ="UPDATE guru SET nama_guru=?, gender=?, alamat=? WHERE nip=?";
        
        try {
            //membuka koneksi ke database menggunakan method konek()
            Connection conn = koneksi.konek();
            //mempersiapkan query SQL dengan parameter (preparedStatment)
            PreparedStatement ps = conn.prepareStatement(sql);
            
            ps.setString(1, namaGuru);//mengisi parameter pertama dengan namaGuru
            
            ps.setString(2, jK);//mengisi parameter kedua dengan Jenis Kelamin("L" atau "P")
            
            ps.setString(3, alamat);//mengisi parameter ketiga dengan alamat
            
            ps.setString(4, NIP);//mengisi parameter ke empat dengan NIP
            
            ps.execute();//menjalankan perintah update untuk menyimpan data ke database
            
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");//untuk menampilkan pesan bahwa data berhasil di ubah
        } catch (SQLException sQLException) {
            //menampilkan pesan jika terjadi kesalahan saat mengubah data
            JOptionPane.showMessageDialog(null,"Data gagal diubah");
        } 
        load_tabel_guru();//memuat ulang data guru di tabel tampilan
        
        reset();//mereset semua input agar kosong kembali
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        //mengambil input NIP dari text field tNIP
        String NIP = tNIP.getText();
       //menyusun perintah / query SQL untuk mengahapus data guru berdasarkan nip
        String sql ="DELETE FROM guru WHERE nip=?";
        
        try {
            //membuka koneksi ke database menggunakan method konek()
            Connection conn = koneksi.konek();
            //mempersiapkan query SQL dengan parameter (preparedStatment)
            PreparedStatement ps = conn.prepareStatement(sql);
            
            ps.setString(1, NIP);//mengisi parameter ke satu dengan NIP
            
            ps.execute();//menjalankan perintah ddelete untuk menyimpan data ke database
            
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");//untuk menampilkan pesan bahwa data berhasil di hapus
        } catch (SQLException sQLException) {
            //menampilkan pesan jika terjadi kesalahan saat menghapus data
            JOptionPane.showMessageDialog(null,"Data gagal dihapus");
        } 
        load_tabel_guru();//memuat ulang data guru di tabel tampilan
        
        reset();//mereset semua input agar kosong kembali
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();//mengosongkan form input dan mengatur ulang komponen input
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblGuruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGuruMouseClicked
        // TODO add your handling code here:
        //mengambil indeks baris yang di kllik oleh user di tabel tblGuru
        int barisYangDipilih = tblGuru.rowAtPoint(evt.getPoint());
        //mengambil nilai NIP dari kolom pertama (indeks 0) pada baris yang dipilih
        String NIP = tblGuru.getValueAt(barisYangDipilih, 0).toString();
        //mengambil nilai nama guru dari kolom kedua (indeks 1) pada baris yang dipilih
        String namaGuru = tblGuru.getValueAt(barisYangDipilih, 1).toString();
        //mengambil nilai jenis kelamin dari kolom ketiga (indeks 2) pada baris yang dipilih
        String jenisKelamin = tblGuru.getValueAt(barisYangDipilih, 2).toString();
        //mengambil nilai alamat dari kolom keempat (indeks 3) pada baris yang dipilih
        String alamat = tblGuru.getValueAt(barisYangDipilih, 3).toString();
        
        tNIP.setText(NIP);// menampilkan nilai NIP ke dalam text field tNIP
        
        tNIP.setEditable(false); //menonaktifkan field tNIP agar tidak bisa di edit(karena NIP berisifat unik dan tdk boleh di ubah)
        
        tNamaGuru.setText(namaGuru);// menampilkan nilai nama guru ke dalam text field tNamaGuru
        
        tAlamat.setText(alamat);// menampilkan nilai alamat ke dalam text field tAlamat
        //mengecheck isi nilai jenis kelamin dan menyesuaikan pilihan pada combo box cJenisKelamin
        switch(jenisKelamin){
                //jika nilai jenis kelamin 'L' set pilihan combo box ke "Laki-Laki"
                case "L":
                cJenisKelamin.setSelectedItem("Laki-Laki");
                break;
                //jika nilai jenis kelamin 'P' set pilihan combo box ke "Perempuan"
                case "P":
                cJenisKelamin.setSelectedItem("Perempuan");
                break;
                //jika nilainya bukan "L" atau "P" kosongkan pilihan combo box
                default :
                cJenisKelamin.setSelectedItem(null);
                break;
    }
    }//GEN-LAST:event_tblGuruMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cJenisKelamin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDataGuru;
    private javax.swing.JLabel lblJenisKelamin;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNip;
    private javax.swing.JPanel pContentGuru;
    private javax.swing.JPanel pHeaderGuru;
    private javax.swing.JPanel pInputan;
    private javax.swing.JPanel pTabel;
    private javax.swing.JPanel pTampilan;
    private javax.swing.JPanel pTombol;
    private javax.swing.JTextField tAlamat;
    private javax.swing.JTextField tNIP;
    private javax.swing.JTextField tNamaGuru;
    private javax.swing.JTable tblGuru;
    // End of variables declaration//GEN-END:variables
}
