/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplikasialumni202557201008;

/**
 *
 * @author Acer
 */
public class panelDashboard extends javax.swing.JPanel {

    /**
     * Creates new form panelDashboard
     */
    public panelDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContentDasbor = new javax.swing.JPanel();
        pHeaderJurusan = new javax.swing.JPanel();
        pJumlahJurusan = new javax.swing.JPanel();
        lblJumlahJurusan = new javax.swing.JLabel();
        lblJurusan = new javax.swing.JLabel();
        pHeaderGuru = new javax.swing.JPanel();
        pJumlahGuru = new javax.swing.JPanel();
        lblJumlahGuru = new javax.swing.JLabel();
        lblGuru = new javax.swing.JLabel();
        pHeaderSiswa = new javax.swing.JPanel();
        pJumlahSiswa = new javax.swing.JPanel();
        lblJumlahSiswa = new javax.swing.JLabel();
        lblSiswa = new javax.swing.JLabel();
        pHeaderKelas = new javax.swing.JPanel();
        pJumlahKelas = new javax.swing.JPanel();
        lblJumlahKelas = new javax.swing.JLabel();
        lblKelas = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 20));
        setLayout(new java.awt.CardLayout());

        PanelContentDasbor.setLayout(new java.awt.GridLayout(1, 4, 20, 0));

        pHeaderJurusan.setMinimumSize(new java.awt.Dimension(200, 150));
        pHeaderJurusan.setName(""); // NOI18N
        pHeaderJurusan.setPreferredSize(new java.awt.Dimension(200, 150));
        pHeaderJurusan.setLayout(new java.awt.BorderLayout());

        pJumlahJurusan.setBackground(new java.awt.Color(255, 255, 255));
        pJumlahJurusan.setMinimumSize(new java.awt.Dimension(766, 150));
        pJumlahJurusan.setPreferredSize(new java.awt.Dimension(766, 150));
        pJumlahJurusan.setLayout(new java.awt.BorderLayout());

        lblJumlahJurusan.setBackground(new java.awt.Color(51, 153, 255));
        lblJumlahJurusan.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 18)); // NOI18N
        lblJumlahJurusan.setForeground(new java.awt.Color(255, 255, 255));
        lblJumlahJurusan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJumlahJurusan.setText("Jumlah Jurusan");
        lblJumlahJurusan.setMaximumSize(new java.awt.Dimension(46, 35));
        lblJumlahJurusan.setMinimumSize(new java.awt.Dimension(46, 35));
        lblJumlahJurusan.setOpaque(true);
        lblJumlahJurusan.setPreferredSize(new java.awt.Dimension(46, 35));
        pJumlahJurusan.add(lblJumlahJurusan, java.awt.BorderLayout.PAGE_START);

        lblJurusan.setBackground(new java.awt.Color(255, 255, 255));
        lblJurusan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblJurusan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJurusan.setText("3");
        lblJurusan.setMaximumSize(new java.awt.Dimension(124, 100));
        lblJurusan.setMinimumSize(new java.awt.Dimension(124, 100));
        lblJurusan.setPreferredSize(new java.awt.Dimension(124, 100));
        pJumlahJurusan.add(lblJurusan, java.awt.BorderLayout.CENTER);

        pHeaderJurusan.add(pJumlahJurusan, java.awt.BorderLayout.PAGE_START);

        PanelContentDasbor.add(pHeaderJurusan);
        pHeaderJurusan.getAccessibleContext().setAccessibleName("");

        pHeaderGuru.setMinimumSize(new java.awt.Dimension(200, 150));
        pHeaderGuru.setPreferredSize(new java.awt.Dimension(200, 150));
        pHeaderGuru.setLayout(new java.awt.BorderLayout());

        pJumlahGuru.setBackground(new java.awt.Color(255, 255, 255));
        pJumlahGuru.setMinimumSize(new java.awt.Dimension(766, 150));
        pJumlahGuru.setPreferredSize(new java.awt.Dimension(766, 150));
        pJumlahGuru.setLayout(new java.awt.BorderLayout());

        lblJumlahGuru.setBackground(new java.awt.Color(51, 153, 255));
        lblJumlahGuru.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 18)); // NOI18N
        lblJumlahGuru.setForeground(new java.awt.Color(255, 255, 255));
        lblJumlahGuru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJumlahGuru.setText("Jumlah Guru");
        lblJumlahGuru.setMaximumSize(new java.awt.Dimension(46, 35));
        lblJumlahGuru.setMinimumSize(new java.awt.Dimension(46, 35));
        lblJumlahGuru.setOpaque(true);
        lblJumlahGuru.setPreferredSize(new java.awt.Dimension(46, 35));
        pJumlahGuru.add(lblJumlahGuru, java.awt.BorderLayout.PAGE_START);

        lblGuru.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGuru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGuru.setText("15");
        lblGuru.setMaximumSize(new java.awt.Dimension(124, 100));
        lblGuru.setMinimumSize(new java.awt.Dimension(124, 100));
        lblGuru.setPreferredSize(new java.awt.Dimension(124, 100));
        pJumlahGuru.add(lblGuru, java.awt.BorderLayout.CENTER);

        pHeaderGuru.add(pJumlahGuru, java.awt.BorderLayout.PAGE_START);

        PanelContentDasbor.add(pHeaderGuru);

        pHeaderSiswa.setMinimumSize(new java.awt.Dimension(200, 150));
        pHeaderSiswa.setPreferredSize(new java.awt.Dimension(200, 150));
        pHeaderSiswa.setLayout(new java.awt.BorderLayout());

        pJumlahSiswa.setBackground(new java.awt.Color(255, 255, 255));
        pJumlahSiswa.setMinimumSize(new java.awt.Dimension(766, 150));
        pJumlahSiswa.setPreferredSize(new java.awt.Dimension(766, 150));
        pJumlahSiswa.setLayout(new java.awt.BorderLayout());

        lblJumlahSiswa.setBackground(new java.awt.Color(51, 153, 255));
        lblJumlahSiswa.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 18)); // NOI18N
        lblJumlahSiswa.setForeground(new java.awt.Color(255, 255, 255));
        lblJumlahSiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJumlahSiswa.setText("Jumlah Siswa");
        lblJumlahSiswa.setMaximumSize(new java.awt.Dimension(46, 35));
        lblJumlahSiswa.setMinimumSize(new java.awt.Dimension(46, 35));
        lblJumlahSiswa.setOpaque(true);
        lblJumlahSiswa.setPreferredSize(new java.awt.Dimension(46, 35));
        pJumlahSiswa.add(lblJumlahSiswa, java.awt.BorderLayout.PAGE_START);

        lblSiswa.setBackground(new java.awt.Color(255, 255, 255));
        lblSiswa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSiswa.setText("300");
        lblSiswa.setMaximumSize(new java.awt.Dimension(124, 100));
        lblSiswa.setMinimumSize(new java.awt.Dimension(124, 100));
        lblSiswa.setPreferredSize(new java.awt.Dimension(124, 100));
        pJumlahSiswa.add(lblSiswa, java.awt.BorderLayout.CENTER);

        pHeaderSiswa.add(pJumlahSiswa, java.awt.BorderLayout.PAGE_START);

        PanelContentDasbor.add(pHeaderSiswa);

        pHeaderKelas.setMinimumSize(new java.awt.Dimension(200, 150));
        pHeaderKelas.setPreferredSize(new java.awt.Dimension(200, 150));
        pHeaderKelas.setLayout(new java.awt.BorderLayout());

        pJumlahKelas.setBackground(new java.awt.Color(255, 255, 255));
        pJumlahKelas.setMinimumSize(new java.awt.Dimension(766, 150));
        pJumlahKelas.setPreferredSize(new java.awt.Dimension(766, 150));
        pJumlahKelas.setLayout(new java.awt.BorderLayout());

        lblJumlahKelas.setBackground(new java.awt.Color(51, 153, 255));
        lblJumlahKelas.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 18)); // NOI18N
        lblJumlahKelas.setForeground(new java.awt.Color(255, 255, 255));
        lblJumlahKelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJumlahKelas.setText("Jumlah Kelas");
        lblJumlahKelas.setMaximumSize(new java.awt.Dimension(46, 35));
        lblJumlahKelas.setMinimumSize(new java.awt.Dimension(46, 35));
        lblJumlahKelas.setOpaque(true);
        lblJumlahKelas.setPreferredSize(new java.awt.Dimension(46, 35));
        pJumlahKelas.add(lblJumlahKelas, java.awt.BorderLayout.PAGE_START);

        lblKelas.setBackground(new java.awt.Color(255, 255, 255));
        lblKelas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblKelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKelas.setText("10");
        lblKelas.setMaximumSize(new java.awt.Dimension(124, 100));
        lblKelas.setMinimumSize(new java.awt.Dimension(124, 100));
        lblKelas.setPreferredSize(new java.awt.Dimension(124, 100));
        pJumlahKelas.add(lblKelas, java.awt.BorderLayout.CENTER);

        pHeaderKelas.add(pJumlahKelas, java.awt.BorderLayout.PAGE_START);

        PanelContentDasbor.add(pHeaderKelas);

        add(PanelContentDasbor, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContentDasbor;
    private javax.swing.JLabel lblGuru;
    private javax.swing.JLabel lblJumlahGuru;
    private javax.swing.JLabel lblJumlahJurusan;
    private javax.swing.JLabel lblJumlahKelas;
    private javax.swing.JLabel lblJumlahSiswa;
    private javax.swing.JLabel lblJurusan;
    private javax.swing.JLabel lblKelas;
    private javax.swing.JLabel lblSiswa;
    private javax.swing.JPanel pHeaderGuru;
    private javax.swing.JPanel pHeaderJurusan;
    private javax.swing.JPanel pHeaderKelas;
    private javax.swing.JPanel pHeaderSiswa;
    private javax.swing.JPanel pJumlahGuru;
    private javax.swing.JPanel pJumlahJurusan;
    private javax.swing.JPanel pJumlahKelas;
    private javax.swing.JPanel pJumlahSiswa;
    // End of variables declaration//GEN-END:variables
}
