/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplikasialumni202557201008;

/**
 *
 * @author Acer
 */
public class panelKelas extends javax.swing.JPanel {

    /**
     * Creates new form panelDashboard
     */
    public panelKelas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pHeaderKelas = new javax.swing.JPanel();
        lblDataKelas = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        pContentKelas = new javax.swing.JPanel();
        pInputan = new javax.swing.JPanel();
        lblKodekelas = new javax.swing.JLabel();
        txtKodekelas = new javax.swing.JTextField();
        lblNamakelas = new javax.swing.JLabel();
        txtNamakelas = new javax.swing.JTextField();
        lblTingkatan = new javax.swing.JLabel();
        cTingkatan = new javax.swing.JComboBox<>();
        cJurusan = new javax.swing.JComboBox<>();
        cWaliKelas = new javax.swing.JComboBox<>();
        lblJurusan = new javax.swing.JLabel();
        lblWalikelas = new javax.swing.JLabel();
        pTampilan = new javax.swing.JPanel();
        pTombolKelas = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        pTabelKelas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataKelas = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 20));
        setMinimumSize(new java.awt.Dimension(782, 622));
        setLayout(new java.awt.BorderLayout());

        pHeaderKelas.setBackground(new java.awt.Color(51, 153, 255));
        pHeaderKelas.setMinimumSize(new java.awt.Dimension(100, 40));
        pHeaderKelas.setPreferredSize(new java.awt.Dimension(100, 40));
        pHeaderKelas.setLayout(new java.awt.BorderLayout());

        lblDataKelas.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        lblDataKelas.setForeground(new java.awt.Color(255, 255, 255));
        lblDataKelas.setText("Data Kelas");
        lblDataKelas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        pHeaderKelas.add(lblDataKelas, java.awt.BorderLayout.LINE_START);

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/close 22.png"))); // NOI18N
        lblClose.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        pHeaderKelas.add(lblClose, java.awt.BorderLayout.LINE_END);

        add(pHeaderKelas, java.awt.BorderLayout.PAGE_START);

        pContentKelas.setLayout(new java.awt.BorderLayout());

        pInputan.setMinimumSize(new java.awt.Dimension(250, 371));
        pInputan.setPreferredSize(new java.awt.Dimension(250, 371));

        lblKodekelas.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblKodekelas.setText("Kode Kelas");

        lblNamakelas.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblNamakelas.setText("Nama Kelas");

        lblTingkatan.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblTingkatan.setText("Tingkatan");

        cTingkatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cWaliKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblJurusan.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblJurusan.setText("Jurusan");

        lblWalikelas.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblWalikelas.setText("Wali Kelas");

        javax.swing.GroupLayout pInputanLayout = new javax.swing.GroupLayout(pInputan);
        pInputan.setLayout(pInputanLayout);
        pInputanLayout.setHorizontalGroup(
            pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInputanLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWalikelas)
                    .addComponent(lblJurusan)
                    .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTingkatan)
                        .addComponent(lblNamakelas)
                        .addComponent(lblKodekelas)
                        .addComponent(txtKodekelas)
                        .addComponent(txtNamakelas, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                        .addComponent(cTingkatan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cJurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cWaliKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pInputanLayout.setVerticalGroup(
            pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInputanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKodekelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKodekelas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNamakelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNamakelas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTingkatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cTingkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblJurusan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWalikelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cWaliKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        pContentKelas.add(pInputan, java.awt.BorderLayout.LINE_START);

        pTampilan.setLayout(new java.awt.BorderLayout());

        btnTambah.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnTambah.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/plus white.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTambah.setMinimumSize(new java.awt.Dimension(72, 23));
        btnTambah.setPreferredSize(new java.awt.Dimension(72, 23));
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        btnUbah.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        btnUbah.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/edit white.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUbah.setMinimumSize(new java.awt.Dimension(72, 23));
        btnUbah.setPreferredSize(new java.awt.Dimension(72, 23));
        btnUbah.addActionListener(this::btnUbahActionPerformed);

        btnHapus.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        btnHapus.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/hapus white.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHapus.setMinimumSize(new java.awt.Dimension(72, 23));
        btnHapus.setPreferredSize(new java.awt.Dimension(72, 23));
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnReset.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnReset.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/reset white.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReset.setMinimumSize(new java.awt.Dimension(72, 23));
        btnReset.setPreferredSize(new java.awt.Dimension(72, 23));
        btnReset.addActionListener(this::btnResetActionPerformed);

        javax.swing.GroupLayout pTombolKelasLayout = new javax.swing.GroupLayout(pTombolKelas);
        pTombolKelas.setLayout(pTombolKelasLayout);
        pTombolKelasLayout.setHorizontalGroup(
            pTombolKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTombolKelasLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pTombolKelasLayout.setVerticalGroup(
            pTombolKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTombolKelasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTombolKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pTampilan.add(pTombolKelas, java.awt.BorderLayout.PAGE_END);

        pTabelKelas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242), 20));
        pTabelKelas.setLayout(new java.awt.CardLayout());

        tblDataKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDataKelas);

        pTabelKelas.add(jScrollPane1, "card2");

        pTampilan.add(pTabelKelas, java.awt.BorderLayout.CENTER);

        pContentKelas.add(pTampilan, java.awt.BorderLayout.CENTER);

        add(pContentKelas, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cJurusan;
    private javax.swing.JComboBox<String> cTingkatan;
    private javax.swing.JComboBox<String> cWaliKelas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDataKelas;
    private javax.swing.JLabel lblJurusan;
    private javax.swing.JLabel lblKodekelas;
    private javax.swing.JLabel lblNamakelas;
    private javax.swing.JLabel lblTingkatan;
    private javax.swing.JLabel lblWalikelas;
    private javax.swing.JPanel pContentKelas;
    private javax.swing.JPanel pHeaderKelas;
    private javax.swing.JPanel pInputan;
    private javax.swing.JPanel pTabelKelas;
    private javax.swing.JPanel pTampilan;
    private javax.swing.JPanel pTombolKelas;
    private javax.swing.JTable tblDataKelas;
    private javax.swing.JTextField txtKodekelas;
    private javax.swing.JTextField txtNamakelas;
    // End of variables declaration//GEN-END:variables
}
