/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplikasialumni202557201008;

/**
 *
 * @author Acer
 */
public class panelAbout extends javax.swing.JPanel {

    /**
     * Creates new form panelDashboard
     */
    public panelAbout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pHeaderAbout = new javax.swing.JPanel();
        lblAbout = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        pContentAbout = new javax.swing.JPanel();
        lblpemilikapk = new javax.swing.JLabel();
        lblNimpemilik = new javax.swing.JLabel();
        lblProdipemilik = new javax.swing.JLabel();
        lblInstitut = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 20));
        setMinimumSize(new java.awt.Dimension(539, 450));
        setLayout(new java.awt.BorderLayout());

        pHeaderAbout.setBackground(new java.awt.Color(51, 153, 255));
        pHeaderAbout.setMinimumSize(new java.awt.Dimension(100, 40));
        pHeaderAbout.setPreferredSize(new java.awt.Dimension(100, 40));
        pHeaderAbout.setLayout(new java.awt.BorderLayout());

        lblAbout.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        lblAbout.setForeground(new java.awt.Color(255, 255, 255));
        lblAbout.setText("About Us");
        lblAbout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        pHeaderAbout.add(lblAbout, java.awt.BorderLayout.LINE_START);

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/close 22.png"))); // NOI18N
        lblClose.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        pHeaderAbout.add(lblClose, java.awt.BorderLayout.LINE_END);

        add(pHeaderAbout, java.awt.BorderLayout.PAGE_START);

        lblpemilikapk.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 14)); // NOI18N
        lblpemilikapk.setText("Aplikasi ini dibuat oleh Muhammad Damar Az Zabarzad");

        lblNimpemilik.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 14)); // NOI18N
        lblNimpemilik.setText("NIM : 12345567");

        lblProdipemilik.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 14)); // NOI18N
        lblProdipemilik.setText("Prodi S1 Sistem Informasi");

        lblInstitut.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 14)); // NOI18N
        lblInstitut.setText("Institut Teknologi Mojosari");

        javax.swing.GroupLayout pContentAboutLayout = new javax.swing.GroupLayout(pContentAbout);
        pContentAbout.setLayout(pContentAboutLayout);
        pContentAboutLayout.setHorizontalGroup(
            pContentAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContentAboutLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pContentAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblpemilikapk)
                    .addComponent(lblNimpemilik, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProdipemilik, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInstitut, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        pContentAboutLayout.setVerticalGroup(
            pContentAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContentAboutLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblpemilikapk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNimpemilik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProdipemilik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstitut)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        add(pContentAbout, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblInstitut;
    private javax.swing.JLabel lblNimpemilik;
    private javax.swing.JLabel lblProdipemilik;
    private javax.swing.JLabel lblpemilikapk;
    private javax.swing.JPanel pContentAbout;
    private javax.swing.JPanel pHeaderAbout;
    // End of variables declaration//GEN-END:variables
}
