/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplikasialumni202557201008;

/**
 *
 * @author Acer
 */
public class panelJurusan extends javax.swing.JPanel {

    /**
     * Creates new form panelDashboard
     */
    public panelJurusan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pContentJurusan = new javax.swing.JPanel();
        pHeaderJurusan = new javax.swing.JPanel();
        lblDataJurusan = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        pInputan = new javax.swing.JPanel();
        lblKodejur = new javax.swing.JLabel();
        lblNamajur = new javax.swing.JLabel();
        txtKodejur = new javax.swing.JTextField();
        txtNamajur = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        pTabelJurusan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataJurusan = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 20));
        setPreferredSize(new java.awt.Dimension(654, 451));
        setLayout(new java.awt.BorderLayout());

        pContentJurusan.setMinimumSize(new java.awt.Dimension(100, 200));
        pContentJurusan.setPreferredSize(new java.awt.Dimension(100, 200));
        pContentJurusan.setLayout(new java.awt.BorderLayout());

        pHeaderJurusan.setBackground(new java.awt.Color(51, 153, 255));
        pHeaderJurusan.setMinimumSize(new java.awt.Dimension(100, 40));
        pHeaderJurusan.setPreferredSize(new java.awt.Dimension(100, 40));
        pHeaderJurusan.setLayout(new java.awt.BorderLayout());

        lblDataJurusan.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        lblDataJurusan.setForeground(new java.awt.Color(255, 255, 255));
        lblDataJurusan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDataJurusan.setText("Data Jurusan");
        lblDataJurusan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        pHeaderJurusan.add(lblDataJurusan, java.awt.BorderLayout.LINE_START);

        lblClose.setBackground(new java.awt.Color(51, 153, 255));
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/close 22.png"))); // NOI18N
        lblClose.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 4));
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        pHeaderJurusan.add(lblClose, java.awt.BorderLayout.LINE_END);

        pContentJurusan.add(pHeaderJurusan, java.awt.BorderLayout.PAGE_START);

        lblKodejur.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblKodejur.setText("Kode Jurusan");

        lblNamajur.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblNamajur.setText("Nama Jurusan ");

        btnTambah.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnTambah.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/plus white.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTambah.setMinimumSize(new java.awt.Dimension(72, 23));
        btnTambah.setPreferredSize(new java.awt.Dimension(72, 23));
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        btnUbah.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        btnUbah.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/edit white.png"))); // NOI18N
        btnUbah.setText("Ubah");

        btnHapus.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        btnHapus.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/hapus white.png"))); // NOI18N
        btnHapus.setText("Hapus");

        btnReset.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnReset.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/reset white.png"))); // NOI18N
        btnReset.setText("Reset");

        javax.swing.GroupLayout pInputanLayout = new javax.swing.GroupLayout(pInputan);
        pInputan.setLayout(pInputanLayout);
        pInputanLayout.setHorizontalGroup(
            pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInputanLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pInputanLayout.createSequentialGroup()
                        .addComponent(txtKodejur, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamajur, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pInputanLayout.createSequentialGroup()
                        .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKodejur, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pInputanLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pInputanLayout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(lblNamajur, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        pInputanLayout.setVerticalGroup(
            pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInputanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKodejur)
                    .addComponent(lblNamajur))
                .addGap(18, 18, 18)
                .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKodejur, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamajur, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        pContentJurusan.add(pInputan, java.awt.BorderLayout.CENTER);

        add(pContentJurusan, java.awt.BorderLayout.PAGE_START);

        pTabelJurusan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242), 20));
        pTabelJurusan.setLayout(new java.awt.CardLayout());

        tblDataJurusan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDataJurusan);

        pTabelJurusan.add(jScrollPane1, "card2");

        add(pTabelJurusan, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDataJurusan;
    private javax.swing.JLabel lblKodejur;
    private javax.swing.JLabel lblNamajur;
    private javax.swing.JPanel pContentJurusan;
    private javax.swing.JPanel pHeaderJurusan;
    private javax.swing.JPanel pInputan;
    private javax.swing.JPanel pTabelJurusan;
    private javax.swing.JTable tblDataJurusan;
    private javax.swing.JTextField txtKodejur;
    private javax.swing.JTextField txtNamajur;
    // End of variables declaration//GEN-END:variables
}
