/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplikasialumni202557201008;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Acer
 */
public class panelGuru extends javax.swing.JPanel {

    /**
     * Creates new form panelDashboard
     */
    public panelGuru() {
        initComponents();
        reset();
        load_tabel_guru();
    }
    void reset(){
        tNIP.setText(null);
        tNIP.setEditable(true);
        tNamaGuru.setText(null);
        cJenisKelamin.setSelectedItem(null);
        tAlamat.setText(null);
    }
    void load_tabel_guru(){
        DefaultTableModel mdl =new DefaultTableModel();
        
        mdl.addColumn("NIP");
        mdl.addColumn("Nama Guru");
        mdl.addColumn("L/P");
        mdl.addColumn("Alamat");
        
        String sql = "SELECT * FROM guru";
        
        try {
            Connection conn = koneksi.konek();

            Statement st = conn.createStatement();

            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                String NIP = rs.getString("nip");
                String namaGuru = rs.getString("nama_guru");
                String jenisKelamin = rs.getString("gender");
                String alamat = rs.getString("alamat");

                Object[] baris = {NIP, namaGuru, jenisKelamin, alamat};

                mdl.addRow(baris);
            }
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null,"Gagal mengambil data");
        }
        
        tblGuru.setModel(mdl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pHeaderGuru = new javax.swing.JPanel();
        lblDataGuru = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        pContentGuru = new javax.swing.JPanel();
        pInputan = new javax.swing.JPanel();
        lblNip = new javax.swing.JLabel();
        tNIP = new javax.swing.JTextField();
        tNamaGuru = new javax.swing.JTextField();
        lblNama = new javax.swing.JLabel();
        cJenisKelamin = new javax.swing.JComboBox<>();
        lblJenisKelamin = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        tAlamat = new javax.swing.JTextField();
        pTampilan = new javax.swing.JPanel();
        pTombol = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        pTabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGuru = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 20));
        setMinimumSize(new java.awt.Dimension(769, 451));
        setPreferredSize(new java.awt.Dimension(769, 451));
        setLayout(new java.awt.BorderLayout());

        pHeaderGuru.setBackground(new java.awt.Color(51, 153, 255));
        pHeaderGuru.setMinimumSize(new java.awt.Dimension(100, 40));
        pHeaderGuru.setPreferredSize(new java.awt.Dimension(100, 40));
        pHeaderGuru.setLayout(new java.awt.BorderLayout());

        lblDataGuru.setBackground(new java.awt.Color(51, 153, 255));
        lblDataGuru.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        lblDataGuru.setForeground(new java.awt.Color(255, 255, 255));
        lblDataGuru.setText("Data Guru");
        lblDataGuru.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        lblDataGuru.setOpaque(true);
        pHeaderGuru.add(lblDataGuru, java.awt.BorderLayout.LINE_START);

        lblClose.setBackground(new java.awt.Color(51, 153, 255));
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/close 22.png"))); // NOI18N
        lblClose.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        lblClose.setOpaque(true);
        pHeaderGuru.add(lblClose, java.awt.BorderLayout.LINE_END);

        add(pHeaderGuru, java.awt.BorderLayout.PAGE_START);

        pContentGuru.setLayout(new java.awt.BorderLayout());

        pInputan.setMinimumSize(new java.awt.Dimension(250, 371));
        pInputan.setPreferredSize(new java.awt.Dimension(250, 371));

        lblNip.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblNip.setText("NIP");

        lblNama.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblNama.setText("Nama");

        cJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan", " " }));

        lblJenisKelamin.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblJenisKelamin.setText("Jenis Kelamin");

        lblAlamat.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblAlamat.setText("Alamat");

        javax.swing.GroupLayout pInputanLayout = new javax.swing.GroupLayout(pInputan);
        pInputan.setLayout(pInputanLayout);
        pInputanLayout.setHorizontalGroup(
            pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInputanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAlamat)
                    .addComponent(lblJenisKelamin)
                    .addComponent(lblNama)
                    .addComponent(lblNip)
                    .addComponent(tNIP)
                    .addComponent(tNamaGuru)
                    .addComponent(cJenisKelamin, 0, 220, Short.MAX_VALUE)
                    .addComponent(tAlamat))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pInputanLayout.setVerticalGroup(
            pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInputanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNIP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNamaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJenisKelamin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAlamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pContentGuru.add(pInputan, java.awt.BorderLayout.LINE_START);

        pTampilan.setLayout(new java.awt.BorderLayout());

        btnTambah.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnTambah.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/plus white.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTambah.setMinimumSize(new java.awt.Dimension(72, 23));
        btnTambah.setPreferredSize(new java.awt.Dimension(72, 23));
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        btnUbah.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        btnUbah.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/edit white.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUbah.setMinimumSize(new java.awt.Dimension(72, 23));
        btnUbah.setPreferredSize(new java.awt.Dimension(72, 23));
        btnUbah.addActionListener(this::btnUbahActionPerformed);

        btnHapus.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        btnHapus.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/hapus white.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHapus.setMinimumSize(new java.awt.Dimension(72, 23));
        btnHapus.setPreferredSize(new java.awt.Dimension(72, 23));
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnReset.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnReset.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/reset white.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReset.setMinimumSize(new java.awt.Dimension(72, 23));
        btnReset.setPreferredSize(new java.awt.Dimension(72, 23));
        btnReset.addActionListener(this::btnResetActionPerformed);

        javax.swing.GroupLayout pTombolLayout = new javax.swing.GroupLayout(pTombol);
        pTombol.setLayout(pTombolLayout);
        pTombolLayout.setHorizontalGroup(
            pTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTombolLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pTombolLayout.setVerticalGroup(
            pTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTombolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTombolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pTampilan.add(pTombol, java.awt.BorderLayout.PAGE_END);

        pTabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242), 20));
        pTabel.setLayout(new java.awt.CardLayout());

        tblGuru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGuruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGuru);

        pTabel.add(jScrollPane1, "card2");

        pTampilan.add(pTabel, java.awt.BorderLayout.CENTER);

        pContentGuru.add(pTampilan, java.awt.BorderLayout.CENTER);

        add(pContentGuru, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String NIP = tNIP.getText();
        
        String namaGuru = tNamaGuru.getText();
        
        String jenisKelamin = cJenisKelamin.getSelectedItem().toString();
        
        String alamat = tAlamat.getText();
        
        String jK = null;
        
        switch (jenisKelamin){
            case "Laki-Laki":
                jK="L";
                break;
            case "Perempuan":
                jK ="P";
                break;
            default:
                jK =null;
                break;
        }
        
        String sql ="INSERT INTO guru(nip, nama_guru, gender, alamat) VALUES(?,?,?,?)";
        
        try {
            Connection conn = koneksi.konek();
            
            PreparedStatement ps = conn.prepareStatement(sql);
            
            ps.setString(1, NIP);
            
            ps.setString(2, namaGuru);
            
            ps.setString(3, jK);
            
            ps.setString(4, alamat);
            
            ps.execute();
            
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null,"Data gagal disimpan");
        } 
        load_tabel_guru();
        
        reset();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        String NIP = tNIP.getText();
        
        String namaGuru = tNamaGuru.getText();
        
        String jenisKelamin = cJenisKelamin.getSelectedItem().toString();
        
        String alamat = tAlamat.getText();
        
        String jK = null;
        
        switch (jenisKelamin){
            case "Laki-Laki":
                jK="L";
                break;
            case "Perempuan":
                jK ="P";
                break;
            default:
                jK =null;
                break;
        }
        
        String sql ="UPDATE guru SET nama_guru=?, gender=?, alamt=? WHERE nip=?";
        
        try {
            Connection conn = koneksi.konek();
            
            PreparedStatement ps = conn.prepareStatement(sql);
            
            ps.setString(1, namaGuru);
            
            ps.setString(2, jK);
            
            ps.setString(3, alamat);
            
            ps.setString(4, NIP);
            
            ps.execute();
            
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null,"Data gagal diubah");
        } 
        load_tabel_guru();
        
        reset();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String NIP = tNIP.getText();
       
        String sql ="DELETE FROM guru WHERE nip=?";
        
        try {
            Connection conn = koneksi.konek();
            
            PreparedStatement ps = conn.prepareStatement(sql);
            
            ps.setString(1, NIP);
            
            ps.execute();
            
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null,"Data gagal dihapus");
        } 
        load_tabel_guru();
        
        reset();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblGuruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGuruMouseClicked
        // TODO add your handling code here:
        int barisYangDipilih = tblGuru.rowAtPoint(evt.getPoint());
        
        String NIP = tblGuru.getValueAt(barisYangDipilih, 0).toString();
        
        String namaGuru = tblGuru.getValueAt(barisYangDipilih, 1).toString();
        
        String jenisKelamin = tblGuru.getValueAt(barisYangDipilih, 2).toString();
        
        String alamat = tblGuru.getValueAt(barisYangDipilih, 3).toString();
        
        tNIP.setText(NIP);
        
        tNIP.setEditable(false);
        
        tNamaGuru.setText(namaGuru);
        
        tAlamat.setText(alamat);
        
        switch(jenisKelamin){
        
                case "L":
                cJenisKelamin.setSelectedItem("Laki-Laki");
                break;
                
                case "P":
                cJenisKelamin.setSelectedItem("Perempuan");
                break;
                
                default :
                cJenisKelamin.setSelectedItem(null);
                break;
    }
    }//GEN-LAST:event_tblGuruMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cJenisKelamin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDataGuru;
    private javax.swing.JLabel lblJenisKelamin;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNip;
    private javax.swing.JPanel pContentGuru;
    private javax.swing.JPanel pHeaderGuru;
    private javax.swing.JPanel pInputan;
    private javax.swing.JPanel pTabel;
    private javax.swing.JPanel pTampilan;
    private javax.swing.JPanel pTombol;
    private javax.swing.JTextField tAlamat;
    private javax.swing.JTextField tNIP;
    private javax.swing.JTextField tNamaGuru;
    private javax.swing.JTable tblGuru;
    // End of variables declaration//GEN-END:variables
}
