/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplikasialumni202557201008;
import java.sql.Connection; // untuk menghubungkan antar java dengan mysql
import java.sql.ResultSet; //menampung hasil query SELECT dari database
import java.sql.SQLException; //untuk menangkap error yang terjadi saat java berinteraksi dengan mysql
import java.sql.Statement; //
/**
 *
 * @author Acer
 */
public class panelDashboard extends javax.swing.JPanel {

    /**
     * Creates new form panelDashboard
     */
    public panelDashboard() { //tempat konstruktor 
        initComponents();
        isiJumlahDataDasbor(); //memanggil method isiJumlahDataDasbor
    }
    private void isiJumlahDataDasbor(){
        //untuk membuka koneksi ke database
        Connection conn = koneksi.konek();
        
        try {
            //mengambil jumlah jurusan dari tabel jurusan
            String sqlJurusan = "SELECT COUNT(*) AS jumlah FROM jurusan";
            Statement psJurusan = conn.createStatement();
            ResultSet rsJurusan = psJurusan.executeQuery(sqlJurusan);
            //jika hasil perintah / query ada, ambil dan tampilkan ke label jumlah jurusan(tJumlahJurusan)
            if (rsJurusan.next()) {
                int jumlah = rsJurusan.getInt("jumlah");
                tJumlahJurusan.setText(String.valueOf(jumlah));
            }
            //mengambil jumlah guru dari tabel guru
            String sqlGuru = "SELECT COUNT(*) AS jumlah FROM guru";
            Statement psGuru = conn.createStatement();
            ResultSet rsGuru = psGuru.executeQuery(sqlGuru);
            //jjika hasil perintah / query ada , ambil dan tampilkan ke label jumlah guru(tJumlahGuru)
            if (rsGuru.next()) {
                int jumlah = rsGuru.getInt("jumlah");
                tJumlahGuru.setText(String.valueOf(jumlah));
            }
            //mengambil jumlah siswa dari tabel siswa
            String sqlSiswa = "SELECT COUNT(*) AS jumlah FROM siswa";
            Statement psSiswa = conn.createStatement();
            ResultSet rsSiswa = psSiswa.executeQuery(sqlSiswa);
            //jika hasil perintah / query ada, ambil dan tampilkan ke label jumlah siswa(tJumlahSiswa)
            if (rsSiswa.next()) {
                int jumlah = rsSiswa.getInt("jumlah");
                tJumlahSiswa.setText(String.valueOf(jumlah));
            }
            //mengambil jumlah kelas dari tabel kelas
            String sqlKelas = "SELECT COUNT(*) AS jumlah FROM kelas";
            Statement psKelas = conn.createStatement();
            ResultSet rsKelas = psKelas.executeQuery(sqlKelas);
            //jika hasil perintah / query ada, ambil dan tampilkan ke label jumlah kelas (tJumlahKelas)
            if (rsKelas.next()) {
                int jumlah = rsKelas.getInt("jumlah");
                tJumlahKelas.setText(String.valueOf(jumlah));
            }
        } catch (SQLException e) {
            //Menampilkan pesan di console, jika terjadi error saat emnagmbil data
            System.err.println("Gagal mengambil jumlah data");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContentDasbor = new javax.swing.JPanel();
        pHeaderJurusan = new javax.swing.JPanel();
        pJumlahJurusan = new javax.swing.JPanel();
        lblJumlahJurusan = new javax.swing.JLabel();
        tJumlahJurusan = new javax.swing.JLabel();
        pHeaderGuru = new javax.swing.JPanel();
        pJumlahGuru = new javax.swing.JPanel();
        lblJumlahGuru = new javax.swing.JLabel();
        tJumlahGuru = new javax.swing.JLabel();
        pHeaderSiswa = new javax.swing.JPanel();
        pJumlahSiswa = new javax.swing.JPanel();
        lblJumlahSiswa = new javax.swing.JLabel();
        tJumlahSiswa = new javax.swing.JLabel();
        pHeaderKelas = new javax.swing.JPanel();
        pJumlahKelas = new javax.swing.JPanel();
        lblJumlahKelas = new javax.swing.JLabel();
        tJumlahKelas = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 20));
        setLayout(new java.awt.CardLayout());

        PanelContentDasbor.setLayout(new java.awt.GridLayout(1, 4, 20, 0));

        pHeaderJurusan.setMinimumSize(new java.awt.Dimension(200, 150));
        pHeaderJurusan.setName(""); // NOI18N
        pHeaderJurusan.setPreferredSize(new java.awt.Dimension(200, 150));
        pHeaderJurusan.setLayout(new java.awt.BorderLayout());

        pJumlahJurusan.setBackground(new java.awt.Color(255, 255, 255));
        pJumlahJurusan.setMinimumSize(new java.awt.Dimension(766, 150));
        pJumlahJurusan.setPreferredSize(new java.awt.Dimension(766, 150));
        pJumlahJurusan.setLayout(new java.awt.BorderLayout());

        lblJumlahJurusan.setBackground(new java.awt.Color(51, 153, 255));
        lblJumlahJurusan.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 18)); // NOI18N
        lblJumlahJurusan.setForeground(new java.awt.Color(255, 255, 255));
        lblJumlahJurusan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJumlahJurusan.setText("Jumlah Jurusan");
        lblJumlahJurusan.setMaximumSize(new java.awt.Dimension(46, 35));
        lblJumlahJurusan.setMinimumSize(new java.awt.Dimension(46, 35));
        lblJumlahJurusan.setOpaque(true);
        lblJumlahJurusan.setPreferredSize(new java.awt.Dimension(46, 35));
        pJumlahJurusan.add(lblJumlahJurusan, java.awt.BorderLayout.PAGE_START);

        tJumlahJurusan.setBackground(new java.awt.Color(255, 255, 255));
        tJumlahJurusan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tJumlahJurusan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tJumlahJurusan.setText("3");
        tJumlahJurusan.setMaximumSize(new java.awt.Dimension(124, 100));
        tJumlahJurusan.setMinimumSize(new java.awt.Dimension(124, 100));
        tJumlahJurusan.setPreferredSize(new java.awt.Dimension(124, 100));
        pJumlahJurusan.add(tJumlahJurusan, java.awt.BorderLayout.CENTER);

        pHeaderJurusan.add(pJumlahJurusan, java.awt.BorderLayout.PAGE_START);

        PanelContentDasbor.add(pHeaderJurusan);
        pHeaderJurusan.getAccessibleContext().setAccessibleName("");

        pHeaderGuru.setMinimumSize(new java.awt.Dimension(200, 150));
        pHeaderGuru.setPreferredSize(new java.awt.Dimension(200, 150));
        pHeaderGuru.setLayout(new java.awt.BorderLayout());

        pJumlahGuru.setBackground(new java.awt.Color(255, 255, 255));
        pJumlahGuru.setMinimumSize(new java.awt.Dimension(766, 150));
        pJumlahGuru.setPreferredSize(new java.awt.Dimension(766, 150));
        pJumlahGuru.setLayout(new java.awt.BorderLayout());

        lblJumlahGuru.setBackground(new java.awt.Color(51, 153, 255));
        lblJumlahGuru.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 18)); // NOI18N
        lblJumlahGuru.setForeground(new java.awt.Color(255, 255, 255));
        lblJumlahGuru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJumlahGuru.setText("Jumlah Guru");
        lblJumlahGuru.setMaximumSize(new java.awt.Dimension(46, 35));
        lblJumlahGuru.setMinimumSize(new java.awt.Dimension(46, 35));
        lblJumlahGuru.setOpaque(true);
        lblJumlahGuru.setPreferredSize(new java.awt.Dimension(46, 35));
        pJumlahGuru.add(lblJumlahGuru, java.awt.BorderLayout.PAGE_START);

        tJumlahGuru.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tJumlahGuru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tJumlahGuru.setText("15");
        tJumlahGuru.setMaximumSize(new java.awt.Dimension(124, 100));
        tJumlahGuru.setMinimumSize(new java.awt.Dimension(124, 100));
        tJumlahGuru.setPreferredSize(new java.awt.Dimension(124, 100));
        pJumlahGuru.add(tJumlahGuru, java.awt.BorderLayout.CENTER);

        pHeaderGuru.add(pJumlahGuru, java.awt.BorderLayout.PAGE_START);

        PanelContentDasbor.add(pHeaderGuru);

        pHeaderSiswa.setMinimumSize(new java.awt.Dimension(200, 150));
        pHeaderSiswa.setPreferredSize(new java.awt.Dimension(200, 150));
        pHeaderSiswa.setLayout(new java.awt.BorderLayout());

        pJumlahSiswa.setBackground(new java.awt.Color(255, 255, 255));
        pJumlahSiswa.setMinimumSize(new java.awt.Dimension(766, 150));
        pJumlahSiswa.setPreferredSize(new java.awt.Dimension(766, 150));
        pJumlahSiswa.setLayout(new java.awt.BorderLayout());

        lblJumlahSiswa.setBackground(new java.awt.Color(51, 153, 255));
        lblJumlahSiswa.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 18)); // NOI18N
        lblJumlahSiswa.setForeground(new java.awt.Color(255, 255, 255));
        lblJumlahSiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJumlahSiswa.setText("Jumlah Siswa");
        lblJumlahSiswa.setMaximumSize(new java.awt.Dimension(46, 35));
        lblJumlahSiswa.setMinimumSize(new java.awt.Dimension(46, 35));
        lblJumlahSiswa.setOpaque(true);
        lblJumlahSiswa.setPreferredSize(new java.awt.Dimension(46, 35));
        pJumlahSiswa.add(lblJumlahSiswa, java.awt.BorderLayout.PAGE_START);

        tJumlahSiswa.setBackground(new java.awt.Color(255, 255, 255));
        tJumlahSiswa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tJumlahSiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tJumlahSiswa.setText("300");
        tJumlahSiswa.setMaximumSize(new java.awt.Dimension(124, 100));
        tJumlahSiswa.setMinimumSize(new java.awt.Dimension(124, 100));
        tJumlahSiswa.setPreferredSize(new java.awt.Dimension(124, 100));
        pJumlahSiswa.add(tJumlahSiswa, java.awt.BorderLayout.CENTER);

        pHeaderSiswa.add(pJumlahSiswa, java.awt.BorderLayout.PAGE_START);

        PanelContentDasbor.add(pHeaderSiswa);

        pHeaderKelas.setMinimumSize(new java.awt.Dimension(200, 150));
        pHeaderKelas.setPreferredSize(new java.awt.Dimension(200, 150));
        pHeaderKelas.setLayout(new java.awt.BorderLayout());

        pJumlahKelas.setBackground(new java.awt.Color(255, 255, 255));
        pJumlahKelas.setMinimumSize(new java.awt.Dimension(766, 150));
        pJumlahKelas.setPreferredSize(new java.awt.Dimension(766, 150));
        pJumlahKelas.setLayout(new java.awt.BorderLayout());

        lblJumlahKelas.setBackground(new java.awt.Color(51, 153, 255));
        lblJumlahKelas.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 18)); // NOI18N
        lblJumlahKelas.setForeground(new java.awt.Color(255, 255, 255));
        lblJumlahKelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJumlahKelas.setText("Jumlah Kelas");
        lblJumlahKelas.setMaximumSize(new java.awt.Dimension(46, 35));
        lblJumlahKelas.setMinimumSize(new java.awt.Dimension(46, 35));
        lblJumlahKelas.setOpaque(true);
        lblJumlahKelas.setPreferredSize(new java.awt.Dimension(46, 35));
        pJumlahKelas.add(lblJumlahKelas, java.awt.BorderLayout.PAGE_START);

        tJumlahKelas.setBackground(new java.awt.Color(255, 255, 255));
        tJumlahKelas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tJumlahKelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tJumlahKelas.setText("10");
        tJumlahKelas.setMaximumSize(new java.awt.Dimension(124, 100));
        tJumlahKelas.setMinimumSize(new java.awt.Dimension(124, 100));
        tJumlahKelas.setPreferredSize(new java.awt.Dimension(124, 100));
        pJumlahKelas.add(tJumlahKelas, java.awt.BorderLayout.CENTER);

        pHeaderKelas.add(pJumlahKelas, java.awt.BorderLayout.PAGE_START);

        PanelContentDasbor.add(pHeaderKelas);

        add(PanelContentDasbor, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContentDasbor;
    private javax.swing.JLabel lblJumlahGuru;
    private javax.swing.JLabel lblJumlahJurusan;
    private javax.swing.JLabel lblJumlahKelas;
    private javax.swing.JLabel lblJumlahSiswa;
    private javax.swing.JPanel pHeaderGuru;
    private javax.swing.JPanel pHeaderJurusan;
    private javax.swing.JPanel pHeaderKelas;
    private javax.swing.JPanel pHeaderSiswa;
    private javax.swing.JPanel pJumlahGuru;
    private javax.swing.JPanel pJumlahJurusan;
    private javax.swing.JPanel pJumlahKelas;
    private javax.swing.JPanel pJumlahSiswa;
    private javax.swing.JLabel tJumlahGuru;
    private javax.swing.JLabel tJumlahJurusan;
    private javax.swing.JLabel tJumlahKelas;
    private javax.swing.JLabel tJumlahSiswa;
    // End of variables declaration//GEN-END:variables
}
