/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplikasialumni202557201008;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Acer
 */
public class panelJurusan extends javax.swing.JPanel {

    /**
     * Creates new form panelDashboard
     */
    public panelJurusan() {
        initComponents();
        reset();
        load_tabel_jurusan();
    }
    void reset(){
        tKodeJurusan.setText(null);
        tKodeJurusan.setEditable(true);
        tNamaJurusan.setText(null);
    }
    void load_tabel_jurusan(){
        DefaultTableModel mdl =new DefaultTableModel();
        
        mdl.addColumn("Kode Jurusan");
        
        mdl.addColumn("Nama Jurusan");
        
        String sql = "SELECT * FROM Jurusan";
        
        try {
            Connection conn = koneksi.konek();

            Statement st = conn.createStatement();

            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                String kodeJurusan = rs.getString("kode_jur");

                String namaJurusan = rs.getString("nama_jur");

                Object[] baris = {kodeJurusan, namaJurusan};

                mdl.addRow(baris);
            }
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null,"Gagal mengambil data!");
        }
        tblJurusan.setModel(mdl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pContentJurusan = new javax.swing.JPanel();
        pHeaderJurusan = new javax.swing.JPanel();
        lblDataJurusan = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        pInputan = new javax.swing.JPanel();
        lblKodejur = new javax.swing.JLabel();
        lblNamajur = new javax.swing.JLabel();
        tKodeJurusan = new javax.swing.JTextField();
        tNamaJurusan = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        pTabelJurusan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJurusan = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 20));
        setMinimumSize(new java.awt.Dimension(654, 451));
        setPreferredSize(new java.awt.Dimension(654, 451));
        setLayout(new java.awt.BorderLayout());

        pContentJurusan.setMinimumSize(new java.awt.Dimension(100, 200));
        pContentJurusan.setPreferredSize(new java.awt.Dimension(100, 200));
        pContentJurusan.setLayout(new java.awt.BorderLayout());

        pHeaderJurusan.setBackground(new java.awt.Color(51, 153, 255));
        pHeaderJurusan.setMinimumSize(new java.awt.Dimension(100, 40));
        pHeaderJurusan.setPreferredSize(new java.awt.Dimension(100, 40));
        pHeaderJurusan.setLayout(new java.awt.BorderLayout());

        lblDataJurusan.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 16)); // NOI18N
        lblDataJurusan.setForeground(new java.awt.Color(255, 255, 255));
        lblDataJurusan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDataJurusan.setText("Data Jurusan");
        lblDataJurusan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        pHeaderJurusan.add(lblDataJurusan, java.awt.BorderLayout.LINE_START);

        lblClose.setBackground(new java.awt.Color(51, 153, 255));
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/close 22.png"))); // NOI18N
        lblClose.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 4));
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        pHeaderJurusan.add(lblClose, java.awt.BorderLayout.LINE_END);

        pContentJurusan.add(pHeaderJurusan, java.awt.BorderLayout.PAGE_START);

        lblKodejur.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblKodejur.setText("Kode Jurusan");

        lblNamajur.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        lblNamajur.setText("Nama Jurusan ");

        btnTambah.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnTambah.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/plus white.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTambah.setMinimumSize(new java.awt.Dimension(72, 23));
        btnTambah.setPreferredSize(new java.awt.Dimension(72, 23));
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        btnUbah.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        btnUbah.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/edit white.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(this::btnUbahActionPerformed);

        btnHapus.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        btnHapus.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/hapus white.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnReset.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnReset.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasialumni202557201008/img/reset white.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        javax.swing.GroupLayout pInputanLayout = new javax.swing.GroupLayout(pInputan);
        pInputan.setLayout(pInputanLayout);
        pInputanLayout.setHorizontalGroup(
            pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInputanLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pInputanLayout.createSequentialGroup()
                        .addComponent(tKodeJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNamaJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pInputanLayout.createSequentialGroup()
                        .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKodejur, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pInputanLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pInputanLayout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(lblNamajur, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        pInputanLayout.setVerticalGroup(
            pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInputanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKodejur)
                    .addComponent(lblNamajur))
                .addGap(18, 18, 18)
                .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tKodeJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNamaJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(pInputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        pContentJurusan.add(pInputan, java.awt.BorderLayout.CENTER);

        add(pContentJurusan, java.awt.BorderLayout.PAGE_START);

        pTabelJurusan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242), 20));
        pTabelJurusan.setLayout(new java.awt.CardLayout());

        tblJurusan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblJurusan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJurusanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblJurusan);

        pTabelJurusan.add(jScrollPane1, "card2");

        add(pTabelJurusan, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        
        String kodeJurusan = tKodeJurusan.getText();
        
        String namaJurusan = tNamaJurusan.getText();
        
        String sql = "INSERT INTO jurusan(kode_jur,nama_jur) VALUES(?,?)";
        
        try {
            Connection conn = koneksi.konek();
            
            PreparedStatement ps = conn.prepareStatement(sql);
            
            ps.setString(1, kodeJurusan);
            
            ps.setString(2, namaJurusan);
            
            ps.execute();
            
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan!");
        } 
        load_tabel_jurusan();
        
        reset();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseMouseClicked

    private void tblJurusanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJurusanMouseClicked
        // TODO add your handling code here:
        int barisYangDipilih=tblJurusan.rowAtPoint(evt.getPoint());
        
        String kodeJurusan =tblJurusan.getValueAt(barisYangDipilih,0).toString();
        
        String namaJurusan =tblJurusan.getValueAt(barisYangDipilih,1).toString();
        
        tKodeJurusan.setText(kodeJurusan);
        
        tKodeJurusan.setEditable(false);
        
        tNamaJurusan.setText(namaJurusan);
    }//GEN-LAST:event_tblJurusanMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        String kodeJurusan = tKodeJurusan.getText();
        
        String namaJurusan = tNamaJurusan.getText();
        
        String sql = "UPDATE jurusan SET nama_jur=? WHERE kode_jur=?";
        
        try {
            Connection conn = koneksi.konek();
            
            PreparedStatement ps = conn.prepareStatement(sql);
            
            ps.setString(1, namaJurusan);
            
            ps.setString(2, kodeJurusan);
            
            ps.execute();
            
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Data gagal diubah!");
        } 
        load_tabel_jurusan();
        
        reset();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String kodeJurusan = tKodeJurusan.getText();
        
        String namaJurusan = tNamaJurusan.getText();
        
        String sql = "DELETE FROM jurusan WHERE kode_jur=?";
        
        try {
            Connection conn = koneksi.konek();
            
            PreparedStatement ps = conn.prepareStatement(sql);
            
            ps.setString(1, kodeJurusan);
            
            ps.execute();
            
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Data gagal dihapus!");
        } 
        load_tabel_jurusan();
        
        reset();
    }//GEN-LAST:event_btnHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDataJurusan;
    private javax.swing.JLabel lblKodejur;
    private javax.swing.JLabel lblNamajur;
    private javax.swing.JPanel pContentJurusan;
    private javax.swing.JPanel pHeaderJurusan;
    private javax.swing.JPanel pInputan;
    private javax.swing.JPanel pTabelJurusan;
    private javax.swing.JTextField tKodeJurusan;
    private javax.swing.JTextField tNamaJurusan;
    private javax.swing.JTable tblJurusan;
    // End of variables declaration//GEN-END:variables
}
