/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplikasialumni202557201008;

/**
 *
 * @author Acer
 */
public class panelDashboard extends javax.swing.JPanel {

    /**
     * Creates new form panelDashboard
     */
    public panelDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pHeaderJurusan = new javax.swing.JPanel();
        pJumlahJurusan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pHeaderGuru = new javax.swing.JPanel();
        pJumlahGuru = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pHeaderSiswa = new javax.swing.JPanel();
        pJumlahSiswa = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pHeaderKelas = new javax.swing.JPanel();
        pJumlahKelas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 20));
        setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 4, 20, 0));

        pHeaderJurusan.setMinimumSize(new java.awt.Dimension(200, 150));
        pHeaderJurusan.setName(""); // NOI18N
        pHeaderJurusan.setPreferredSize(new java.awt.Dimension(200, 150));
        pHeaderJurusan.setLayout(new java.awt.BorderLayout());

        pJumlahJurusan.setBackground(new java.awt.Color(255, 255, 255));
        pJumlahJurusan.setMinimumSize(new java.awt.Dimension(766, 150));
        pJumlahJurusan.setPreferredSize(new java.awt.Dimension(766, 150));
        pJumlahJurusan.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(51, 153, 255));
        jLabel1.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jumlah Jurusan");
        jLabel1.setMaximumSize(new java.awt.Dimension(46, 35));
        jLabel1.setMinimumSize(new java.awt.Dimension(46, 35));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(46, 35));
        pJumlahJurusan.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("3");
        jLabel2.setMaximumSize(new java.awt.Dimension(124, 100));
        jLabel2.setMinimumSize(new java.awt.Dimension(124, 100));
        jLabel2.setPreferredSize(new java.awt.Dimension(124, 100));
        pJumlahJurusan.add(jLabel2, java.awt.BorderLayout.CENTER);

        pHeaderJurusan.add(pJumlahJurusan, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(pHeaderJurusan);
        pHeaderJurusan.getAccessibleContext().setAccessibleName("");

        pHeaderGuru.setMinimumSize(new java.awt.Dimension(200, 150));
        pHeaderGuru.setPreferredSize(new java.awt.Dimension(200, 150));
        pHeaderGuru.setLayout(new java.awt.BorderLayout());

        pJumlahGuru.setBackground(new java.awt.Color(255, 255, 255));
        pJumlahGuru.setMinimumSize(new java.awt.Dimension(766, 150));
        pJumlahGuru.setPreferredSize(new java.awt.Dimension(766, 150));
        pJumlahGuru.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(51, 153, 255));
        jLabel3.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Jumlah Guru");
        jLabel3.setMaximumSize(new java.awt.Dimension(46, 35));
        jLabel3.setMinimumSize(new java.awt.Dimension(46, 35));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(46, 35));
        pJumlahGuru.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("15");
        jLabel4.setMaximumSize(new java.awt.Dimension(124, 100));
        jLabel4.setMinimumSize(new java.awt.Dimension(124, 100));
        jLabel4.setPreferredSize(new java.awt.Dimension(124, 100));
        pJumlahGuru.add(jLabel4, java.awt.BorderLayout.CENTER);

        pHeaderGuru.add(pJumlahGuru, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(pHeaderGuru);

        pHeaderSiswa.setMinimumSize(new java.awt.Dimension(200, 150));
        pHeaderSiswa.setPreferredSize(new java.awt.Dimension(200, 150));
        pHeaderSiswa.setLayout(new java.awt.BorderLayout());

        pJumlahSiswa.setBackground(new java.awt.Color(255, 255, 255));
        pJumlahSiswa.setMinimumSize(new java.awt.Dimension(766, 150));
        pJumlahSiswa.setPreferredSize(new java.awt.Dimension(766, 150));
        pJumlahSiswa.setLayout(new java.awt.BorderLayout());

        jLabel5.setBackground(new java.awt.Color(51, 153, 255));
        jLabel5.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Jumlah Siswa");
        jLabel5.setMaximumSize(new java.awt.Dimension(46, 35));
        jLabel5.setMinimumSize(new java.awt.Dimension(46, 35));
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(46, 35));
        pJumlahSiswa.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("300");
        jLabel6.setMaximumSize(new java.awt.Dimension(124, 100));
        jLabel6.setMinimumSize(new java.awt.Dimension(124, 100));
        jLabel6.setPreferredSize(new java.awt.Dimension(124, 100));
        pJumlahSiswa.add(jLabel6, java.awt.BorderLayout.CENTER);

        pHeaderSiswa.add(pJumlahSiswa, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(pHeaderSiswa);

        pHeaderKelas.setMinimumSize(new java.awt.Dimension(200, 150));
        pHeaderKelas.setPreferredSize(new java.awt.Dimension(200, 150));
        pHeaderKelas.setLayout(new java.awt.BorderLayout());

        pJumlahKelas.setBackground(new java.awt.Color(255, 255, 255));
        pJumlahKelas.setMinimumSize(new java.awt.Dimension(766, 150));
        pJumlahKelas.setPreferredSize(new java.awt.Dimension(766, 150));
        pJumlahKelas.setLayout(new java.awt.BorderLayout());

        jLabel7.setBackground(new java.awt.Color(51, 153, 255));
        jLabel7.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Jumlah Kelas");
        jLabel7.setMaximumSize(new java.awt.Dimension(46, 35));
        jLabel7.setMinimumSize(new java.awt.Dimension(46, 35));
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(46, 35));
        pJumlahKelas.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("10");
        jLabel8.setMaximumSize(new java.awt.Dimension(124, 100));
        jLabel8.setMinimumSize(new java.awt.Dimension(124, 100));
        jLabel8.setPreferredSize(new java.awt.Dimension(124, 100));
        pJumlahKelas.add(jLabel8, java.awt.BorderLayout.CENTER);

        pHeaderKelas.add(pJumlahKelas, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(pHeaderKelas);

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pHeaderGuru;
    private javax.swing.JPanel pHeaderJurusan;
    private javax.swing.JPanel pHeaderKelas;
    private javax.swing.JPanel pHeaderSiswa;
    private javax.swing.JPanel pJumlahGuru;
    private javax.swing.JPanel pJumlahJurusan;
    private javax.swing.JPanel pJumlahKelas;
    private javax.swing.JPanel pJumlahSiswa;
    // End of variables declaration//GEN-END:variables
}
